typesafehub/sbt-conductr

README.md
project/Dependencies.scala
src/main/scala/com/typesafe/typesafeconductr/sbt/SbtTypesafeConductR.scala

The `sbt-bundle` `ConductR` config has been renamed to `Bundle`.
Documentation has also been improved.

Cater for the new Bundle config

---

build.sbt
project/Dependencies.scala
src/main/scala/com/typesafe/typesafeconductr/ConductRController.scala
src/main/scala/com/typesafe/typesafeconductr/console/Columns.scala
src/main/scala/com/typesafe/typesafeconductr/package.scala
src/main/scala/com/typesafe/typesafeconductr/sbt/SbtTypesafeConductR.scala
src/test/scala/com/typesafe/typesafeconductr/ConductRControllerSpec.scala

bundleInfo command was broken, because it assumed outdated JSON format.
This builds on top of #16, therefore only last commit is relevant.

Fix bundleInfo command

---

build.sbt
project/Dependencies.scala
src/main/scala/com/typesafe/typesafeconductr/ConductRController.scala
src/main/scala/com/typesafe/typesafeconductr/console/Columns.scala
src/main/scala/com/typesafe/typesafeconductr/console/Console.scala
src/main/scala/com/typesafe/typesafeconductr/console/Screen.scala
src/main/scala/com/typesafe/typesafeconductr/package.scala
src/main/scala/com/typesafe/typesafeconductr/sbt/SbtTypesafeConductR.scala
src/test/scala/com/typesafe/typesafeconductr/ConductRControllerSpec.scala

`bundleInfo` command now prints bundle information and quits by default. Previous full-screen refreshing mode (now under `-r` flag) is still there, mainly because it was easy to have both modes.
This builds on #16 and #18, thus only last commit is worthy a review.

Print and quit in bundleInfo

---

README.md
src/main/scala/com/typesafe/conductr/sbt/SbtTypesafeConductR.scala
src/test/scala/com/typesafe/conductr/client/ConductRControllerSpec.scala
src/test/scala/com/typesafe/conductr/sbt/SbtTypesafeConductRSpec.scala

+ improves conductr url setting from the console, and smater default

---

project/Dependencies.scala
src/main/scala/com/typesafe/conductr/client/package.scala

It looks like in Play 2.4 they have improved the macro for `Json.format` such that it accepts qualified type names like `ConductRController.Attributes`. For Play 2.3 we have to use imports and simple type names like `Attributes`.

Downgrade to Play 2.3.8 (closes #86)

---

src/main/scala/com/typesafe/conductr/sbt/console/Column.scala
src/main/scala/com/typesafe/conductr/sbt/console/Console.scala
src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala

The spacer failed under the circumstances where there were no rows. I suspect it may also have failed for circumstances where there was more than one row also.

The newly introduced spacer caused a transpose error

---

README.md
project/Dependencies.scala
sbt-conductr-tester/build.sbt
src/main/scala/com/typesafe/conductr/client/ConductRController.scala
src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala

As there is just one ConductR running in the background the scope of most settings should be global.
Input parsing has also been tidied up.
Also upgraded the plugin's dependencies to the latest versions including akka-http.
Fixes #99 
Fixes #98

Addresses global scope

---

README.md
build.sbt
project/Dependencies.scala
src/main/scala/com/typesafe/conductr/client/ConductRController.scala
src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
src/main/scala/com/typesafe/conductr/sbt/console/Column.scala
src/main/scala/com/typesafe/conductr/sbt/console/Console.scala

Implementation of the commands `events` and `logs`. Syntax:
```
conduct logs visualizer
conduct logs conductr-kibana --scale 50
conduct events visualizer
conduct events conductr-kibana --scale 50
```
The last parameter 50 is optional and tells how many lines should be displayed.
The logs and events are getting retrieved. However, the PR isn't finished yet. Missing pieces are:
- Nice formatting of output
Also refactored the `src/main/scala/com/typesafe/conductr/client/ConductRController.scala` by encapsulating duplicated code into methods.

Implementation of events and logs commands

---

src/main/scala/com/typesafe/conductr/sbt/console/Console.scala

Fixes issue #102.
So far the cursor position has been saved and restored after the output has been rendered. This resulted into having the sbt console cursor inside of the output. 
Not sure why this logic has been applied in the first place.
@huntc: Do you have any insights here?
The refresh mode is currently not used by any of the commands.

Fix wrong cursor position in conduct info, events, logs

---

src/main/scala/com/typesafe/conductr/client/ConductRController.scala

ConductR is returning the status code 300 '300 Multiple Choices' in case the http request is ambiguous. in Akka HTTP the status code 300 is part of the `redirection` group. The redirection group returns `true` for the method `status.isSuccess`. In `sbt-conductr` we only validated the status code based on the method `status.isSuccess`. Now an additional check has been added which is validating if the status code is 300. If that is the case an `IllegalStateException` is thrown, as with other errors.

Throw error if http status code 300

---

README.md
src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala

The conduct commands provide now helpful usage information in case the command was not used correctly:
- `conduct` | `conduct help` => Usage information of conduct command
- `conduct [subtask] => Usage information of the particular subtask (only if the parsing of the command failed)
The usage information are the same as on `conductr-cli`.

Adding usage info to conduct commands

---

src/main/scala/com/typesafe/conductr/client/ConductRController.scala
src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
src/test/scala/com/typesafe/conductr/client/ConductRControllerSpec.scala

Restrict the `--affinity` switch for version 1.1 onwards

Implement Affinity switch for `conduct run` task

---

src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
src/main/scala/com/typesafe/conductr/sbt/console/AnsiConsole.scala

The current error handling of `docker-machine` is not optimal. If the VM has not been started with `docker-machine start default` and the user start the sbt session then he will only see this output currently:
```
...
host is not running
[info] Set current project to sbt-conductr-tester (in build file:/Users/mj/workspace/sbt-conductr/sbt-conductr-tester/)
[info] Control Protocol set for http://:9005. Use 'controlServer {ip-address}' to set an alternate address.
```
The error message `host is not running` comes straight from docker machine. The user doesn't now what to do here. This PR improves the output if the VM has not been started yet with `docker-machine`. The new output is:
```
...
host is not running
[warn] Docker VM has not been started. Use 'docker-machine start default' in the …
```

Better error handling to resolve host ip

---

src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala

Removes uneccessary line that adds an empty `Seq` to the the `Keys.commands` key.

No not set empty command seq

---

project/Build.scala
src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/main/scala/com/lightbend/conductr/sbt/Import.scala
src/sbt-test/sbt-conductr/conduct-common-args/project/plugins.sbt
src/sbt-test/sbt-conductr/conduct-end-to-end/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-all-args/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-basic/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-conductr-roles/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-ports-basic/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-ports-multi-module/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-scaling/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-with-features/project/plugins.sbt
src/sbt-test/sbt-conductr/sandbox-with-rp-license/project/plugins.sbt

- Change package of sbt-conductr to `com.lightbend.conductr.sbt`
- Change organization to `com.lightbend.conductr`
The README hasn't been updated on purposes because this version is not published yet. Before we publish the new version we will update the README accordingly to reflect the new organization name.

Change package to com.lightbend.conductr

---

build.sbt
project/Dependencies.scala

Tested this version with a new project that brings in `sbt-conductr`.

Removing unneccesary resolvers

---

src/main/scala/com/lightbend/conductr/sbt/LagomBundleImport.scala
src/main/scala/com/lightbend/conductr/sbt/LagomBundlePlugin.scala

`LagomBundleKeys.endpointsPort` is deprecated. However, we set a default for this key in `LagomBundlePlugin`. Therefore for every Lagom project we currently get a warning that this key is depracted.
Instead we can remove this key because this change will be released as the version 2.0.0. This indicates that this is a breaking change.

Drop LagomBundleKeys.endpointsPort

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

Update `LatestConductrVersion` from 1.1.2 to 1.1.3.
Also removing the default from `conductrImageVersion`. As a consequence `sandbox run` is not picking up the latest ConductR image version anymore. Instead this error message is displayed:
```
The version of the ConductR Docker image must be set.
Please visit https://www.typesafe.com/product/conductr/developer to obtain the current version information.
```
This is the same behavior as one the conductr-cli.

Bump ConductR version to 1.1.3

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

The last PR moved the "conduct" command to the build scope. This was an oversight in that it requires project settings. The command's scope has been restored.

"conduct load <tab>" no longer worked

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

With docker 1.12 the single quote in the `docker ps` command was interpreted as two single quotes by docker and therefore resulted into this error:
```
Error response from daemon: Invalid filter ''name'
```
This PR fixes the error by using double quotes instead of single quotes.

Using double quotes in docker command

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/lagom-conductr-bundle/play-and-lagom-service/test
src/sbt-test/sbt-conductr/conduct-end-to-end/test
src/sbt-test/sbt-conductr/sandbox-all-args/test
src/sbt-test/sbt-conductr/sandbox-conductr-roles/test
src/sbt-test/sbt-conductr/sandbox-ports-basic/test
src/sbt-test/sbt-conductr/sandbox-ports-multi-module/test
src/sbt-test/sbt-conductr/sandbox-ports-override-endpoints/test
src/sbt-test/sbt-conductr/sandbox-scaling/test
src/sbt-test/sbt-conductr/sandbox-with-features/test
src/sbt-test/sbt-conductr/sandbox-with-lagom-project/test
src/sbt-test/sbt-conductr/sandbox-with-play-project/test
src/sbt-test/sbt-conductr/sandbox-with-scala-project/test

ConductR images support semantic versioning, which also means the addition of a `-rc.1` style of suffix. Prior to this PR, declaring `sandbox run 1.1.8-rc.1` did not parse. It now does.

Correct semver handling for image

---

src/main/scala/com/lightbend/conductr/sbt/package.scala

The latest conductr-lib fixes a problem where the service locator would cache the fact that an address could not be found.

Latest conductr-lib

---

src/main/scala/com/lightbend/conductr/sbt/package.scala
src/test/scala/com/lightbend/conductr/sbt/PackageSpec.scala

This is due to the fact that Lagom will support semantic versioning, and hence all releases within the same major versions will be binary compatible.
Also upgrade to ConductR Bundle Lib 1.4.8 since ConductR Bundle Lib 1.4.8 has been made with Lagom's use of semantic versioning.

Use Lagom major version only when resolving ConductR Bundle Lib for Lagom

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/sbt-conductr/sandbox-with-features/test

The `sandbox run` parser supports now the following `--feature` format:
```
sandbox run 1.1.9 --feature monitoring
sandbox run 1.1.9 --feature monitoring v2
sandbox run 1.1.9 --feature monitoring 2.1.0-RC2
```
Allowed format: `--feature <name> <optional_arg>`
`conductr-cli` will then check if the given feature is valid.

Fix sandbox run feature parser

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

Revert the `sandbox run --feature` fix https://github.com/typesafehub/sbt-conductr/pull/174. This fix was unnecessary and worsened the user experience. See this comment for more details: https://github.com/typesafehub/sbt-conductr/pull/174#discussion_r84604593

Revert --features fix

---

.travis.yml
src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala

The start command must always be expressed in Unix file path terms, nothing else (including Windows).

Windows file paths for start command

---

src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
src/sbt-test/bundle-plugin/acl-empty-request-mapping/build.sbt
src/sbt-test/lagom-bundle-plugin/multi-projects-single-acl/build.sbt

ConductR 1.1 always expect Endpoint to declare services URI. As such, always generate empty services URI by default if no request mappings is specified.

Fix compatibility issue with ConductR 1.1

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/sbt-conductr/conduct-end-to-end/test

The `conduct` sub command `services` has been renamed to `service-names` in the lastest conductr-cli. This PR also applies this change to `sbt-conductr`.

Rename services to service-names

---

README.md
sbt-conductr-tester/bundle/build.sbt
src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
src/sbt-test/bundle-plugin/acl-empty-request-mapping/build.sbt
src/sbt-test/bundle-plugin/acl-no-service-name/build.sbt
src/sbt-test/bundle-plugin/basic/build.sbt
src/sbt-test/bundle-plugin/bundle-config/build.sbt
src/sbt-test/bundle-plugin/checks/build.sbt
src/sbt-test/bundle-plugin/overlays/build.sbt
src/sbt-test/bundle-plugin/validation-acl-and-service/build.sbt
src/sbt-test/bundle-plugin/validation-min-memory/build.sbt
src/sbt-test/bundle-plugin/validation-min-memory/project/build.properties
src/sbt-test/bundle-plugin/validation-min-memory/project/plugins.sbt
src/sbt-test/bundle-plugin/validation-min-memory/test
src/sbt-test/lagom-bundle-plugin/play-and-lagom-service/build.sbt
src/sbt-test/play-bundle-plugin/custom-config/build.sbt
src/sbt-test/sbt-conductr/conduct-common-args/build.sbt
src/sbt-test/sbt-conductr/conduct-end-to-end/build.sbt
src/sbt-test/sbt-conductr/sandbox-all-args/build.sbt
src/sbt-test/sbt-conductr/sandbox-conductr-roles/build.sbt
src/sbt-test/sbt-conductr/sandbox-ports-basic/build.sbt
src/sbt-test/sbt-conductr/sandbox-ports-multi-module/build.sbt
src/sbt-test/sbt-conductr/sandbox-ports-override-endpoints/build.sbt
src/sbt-test/sbt-conductr/sandbox-scaling/build.sbt
src/sbt-test/sbt-conductr/sandbox-with-features/build.sbt
src/sbt-test/sbt-conductr/sandbox-with-rp-license/build.sbt

This memory checking verification should help users avoid specifying resident memory values that are too low at runtime.

Validates resident memory

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

Adds `sandbox ps` command to `sbt-conductr` to wrap @fsat's recent commit to `conductr-cli`

add support for recently added `sandbox ps` command

---

.travis.yml
bin/create-credentials.sh

Adding Lightbend credentials to Bintray so that the sbt scripted tests on travis can download the reactive maps bundles from Bintray.

Add Lightbend credentials to travis

---

.travis.yml
src/sbt-test/lagom-conductr-bundle/lagom-service/test
src/sbt-test/sbt-conductr/conduct-end-to-end/test

By pre-loading all that we need, and executing our CLI in offline mode, things go a bit faster.

Warm up the CLI caches

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

This adds `sandbox logs` to the SBT console, inline with the other commands such as `sandbox ps`, etc. Since the acceptance tests call the sandbox via this plugin for all of their functionality, this is being added for consistency and completeness.
Manual Test:
```
[root]> sandbox logs
2017-02-15T16:17:59Z meddle INFO  Slf4jLogger [] - Slf4jLogger started
2017-02-15T16:17:59Z meddle INFO  Slf4jLogger [] - Slf4jLogger started
2017-02-15T16:17:59Z meddle INFO  Slf4jLogger [] - Slf4jLogger started
2017-02-15T16:17:59Z meddle INFO  Slf4jLogger [] - Slf4jLogger started
2017-02-15T16:17:59Z meddle INFO  Slf4jLogger [] - Slf4jLogger started
[success] Total time: 0 s, completed Feb 15, 2017 10:48:20 AM
```

add `sandbox logs` sbt command for completeness

---

src/main/resources/bundle-configuration/cassandra-acls/runtime-config.sh
src/main/resources/bundle-configuration/cassandra-services/runtime-config.sh
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-acls/build.sbt
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-services/build.sbt

The custom Cassandra configuration inside the `cassandra-conf` directory was not correctly included because the `export` command had a bug.
```
4036200951222982399/463d43f142f64d464b50b38a7790fc41635d988f00188a9311b0634cd3d7211d/cassandra-configuration/runtime-config.sh: line 3: export: `=/Users/mj/.conductr/images/tmp/conductr-agent/192.168.10.1/bundles/4f71ca2fc8760ddabadfd8bdcdfbfbcc-463d43f142f64d464b50b38a7790fc41/execution-0-4036200951222982399/cassandra-conf': not a valid identifier
```
Now this custom Cassandra configuration is used.

Export custom cassandra configuration

---

README.md

There's a typo in the `cassandra-configuration:dist` command.
```
> cassandra:configuration:dist
[error] Expected '::'
[error] cassandra:configuration:dist
[error]                         ^
> cassandra-configuration:dist
[info] Cassandra bundle configuration has been created: ...
...
[success] Total time: 4 s, completed Feb 16, 2017 2:17:09 PM
```

Fixes `cassandra-configuration` command syntax

---

.travis.yml

In the past we have used a hack to install Docker on the Travis build machine. This hack is now not working because docker can not be downloaded from a repository anymore: https://travis-ci.org/typesafehub/sbt-conductr/builds/202650049
```
W: Failed to fetch http://ppa.launchpad.net/rwky/redis/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
```
This PR is now using the Travis docker service. This service is officially supported by Travis.

Use Travis docker service

---

src/main/resources/bundle-configuration/cassandra-acls/runtime-config.sh
src/main/resources/bundle-configuration/cassandra-services/runtime-config.sh
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-acls/build.sbt
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-services/build.sbt

Setting Cassandra configuration directory to the bundle configuration directory.
Fixes https://github.com/typesafehub/sbt-conductr/issues/202.

Setting the correct cassandra configuration

---

README.md

Document that different sbt-conductr versions need to be used depending on the project.

Document sbt-conductr 2.2.5 and 2.3.0-rc.1

---

README.md
src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
src/sbt-test/bundle-plugin/acl-empty-request-mapping/build.sbt
src/sbt-test/bundle-plugin/acl-no-service-name/build.sbt
src/sbt-test/bundle-plugin/basic/build.sbt
src/sbt-test/bundle-plugin/checks/build.sbt
src/sbt-test/bundle-plugin/overlays/build.sbt
src/sbt-test/bundle-plugin/validation-acl-and-service/build.sbt
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-acls/build.sbt
src/sbt-test/lagom-bundle-plugin/cassandra-configuration-services/build.sbt
src/sbt-test/lagom-bundle-plugin/multi-projects-single-acl/build.sbt
src/sbt-test/lagom-bundle-plugin/multi-projects/build.sbt
src/sbt-test/lagom-bundle-plugin/multi-services-one-project-same-service-name/build.sbt
src/sbt-test/lagom-bundle-plugin/play-and-lagom-service-java/build.sbt
src/sbt-test/lagom-bundle-plugin/with-service-endpoint-java/build.sbt
src/sbt-test/play-bundle-plugin/custom-config/build.sbt
src/sbt-test/play-bundle-plugin/play24/build.sbt
src/sbt-test/play-bundle-plugin/play25/build.sbt
src/test/scala/com/lightbend/conductr/sbt/ConductrVersionSpec.scala

Cherry pick of https://github.com/typesafehub/sbt-conductr/pull/215 for 2.2.x branch.

Use conductrTargetVersion V2_0 as default (2.2)

---

.travis.yml

Same thing as the other PRs, this time for `sbt-conductr`. Explanation from https://github.com/typesafehub/conductr-cli/pull/327
> Fixes a bug with setting up address aliases. While we do want to use /24 (i.e. 255.255.255.0) for finding a network address to use, we actually always want to create the alias with a /32 (i.e. 255.255.255.255) subnet mask, as the alias itself is only interested in traffic sent directly to it. This fixes a bug on some operating systems (e.g. newer linux 4.x kernels) where network aliases respond to traffic in the same subnet -- even though it's destined for other IPs.
> 
> These changes are appropriate for MacOS as well. If other team members running MacOS could verify that your sandbox works when aliases are created with 255.255.255.255 as well, I think we're …

Fix netmask setup for aliases

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/sbt-conductr/sandbox-all-args/test

This adds support for newly added `sandbox run --no-default-features` argument. See https://github.com/typesafehub/conductr-cli/pull/325

Add support for newly added `sandbox run --no-default-features` argument

---

.travis.yml
README.md
src/main/scala/com/lightbend/conductr/sbt/ConductRImport.scala
src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/sbt-conductr/conduct-common-args/test
src/sbt-test/sbt-conductr/sandbox-all-args/test
src/sbt-test/sbt-conductr/sandbox-conductr-roles/test
src/sbt-test/sbt-conductr/sandbox-end-to-end/test

This will ensure SBT commands indicate an error has occurred if one has. Fixes #207.
I think this is reasonable behavior, as a user I would expect SBT commands to indicate an error has occurred if the commands are reliant on a subprocess exiting successfully.
Manual test:
```
[eslite]> sandbox run
The version of ConductR need to be set.
Please visit https://www.lightbend.com/product/conductr/developer to obtain the current version information.
[error] ({.}/*:sandboxRunTaskInternal) java.lang.IllegalArgumentException: requirement failed: sandbox exited with 1
[error] ({.}/*:sandbox) java.lang.IllegalArgumentException: requirement failed: sandbox exited with 1
[error] Total time: 2 s, completed Feb 21, 2017 10:33:25 AM
```

Rework subprocess execution to check return code when using `.!` and fix tests

---

src/sbt-test/lagom-bundle-plugin/multi-services-one-project-same-service-name/payment-impl/src/main/java/impl/PaymentModule.java

See http://www.lagomframework.com/documentation/1.3.x/java/ServiceImplementation.html: 
>  Lagom allows you to bind multiple services, however, bindServices() may only be invoked once, as this will bind a router for Play to use to route Lagom service calls, which if bound multiple times, will cause a Guice configuration error. The first binding you specify will be considered the primaryServiceBinding and its Descriptor’s name will be used to name your Service. This name will be used by Lagom as the default value to identify your microservice when interacting with other microservices.

bindServices must be invoked exactly once.

---

.travis.yml

Currently, on Travis we install the master state of the conductr-cli. This can lead to errors in case that the latest commit has errors or is not compatible with released ConductR versions. See https://github.com/typesafehub/sbt-conductr/pull/226#issuecomment-285321013
This PR is installing the latest conductr-cli release on Travis instead. Also, for the other Prod-Suite components we are using the latest release instead of a snapshot version, e.g. ConductR, cinnamon, etc.

Travis: Use latest conductr-cli release

---

.travis.yml

Reverting PR https://github.com/typesafehub/sbt-conductr/pull/227 because it actually makes sense to test the conductr-cli master branch. sbt-conductr heavily relies on the conductr-cli and we do not have integration tests in the conductr-cli project. So the sbt-conductr integration tests are also the integration tests of the conductr-cli.
Therefore it makes sense to use the latest commit of the master branch instead of the latest conductr-cli release.
This way, we will catch errors before releasing a new conductr-cli version.

Travis: Use conductr-cli master branch

---

.travis.yml
src/sbt-test/sbt-conductr/sandbox-conductr-roles/build.sbt
src/sbt-test/sbt-conductr/sandbox-conductr-roles/test

The developer license we are using on our Jenkins server only supports 3 ConductR agents. This PR is adjusting the sbt tests so that we test with maximum 3 agents.

Use max 3 ConductR instances

---

.travis.yml
src/sbt-test/sbt-conductr/sandbox-conductr-roles/build.sbt
src/sbt-test/sbt-conductr/sandbox-conductr-roles/test

The developer license we are using on our Jenkins server only supports 3 ConductR agents. This PR is adjusting the sbt tests so that we test with maximum 3 agents.

Use max 3 ConductR instances (2.2.x)

---

src/sbt-test/lagom-conductr-bundle/lagom-scala-service/build.sbt
src/sbt-test/lagom-conductr-bundle/lagom-scala-service/lagom-service-api/src/main/scala/api/FooService.scala
src/sbt-test/lagom-conductr-bundle/lagom-scala-service/lagom-service-impl/src/main/scala/impl/FooServiceImpl.scala
src/sbt-test/lagom-conductr-bundle/lagom-scala-service/project/Build.scala
src/sbt-test/lagom-conductr-bundle/lagom-scala-service/project/plugins.sbt
src/sbt-test/lagom-conductr-bundle/lagom-scala-service/test

This is the scala equivalent of #232 to fix #231.
Improves scripted test that deploys a LagomScala service to awaits until it's reported as started by `conduct info` and then await's until there's a successful HTTP request via the sandbox service gateway.

Deploy and run a LagomScala service

---

sbt-conductr-tester/lagom-bundle/README.md
sbt-conductr-tester/lagom-bundle/build.sbt
sbt-conductr-tester/lagom-bundle/lagom-service-api/src/main/java/api/FooService.java
sbt-conductr-tester/lagom-bundle/lagom-service-impl/src/main/java/impl/FooServiceImpl.java
sbt-conductr-tester/lagom-bundle/lagom-service-impl/src/main/java/impl/Module.java
sbt-conductr-tester/lagom-bundle/play-service/app/Module.java
sbt-conductr-tester/lagom-bundle/play-service/app/controllers/MyController.scala
sbt-conductr-tester/lagom-bundle/play-service/conf/routes
sbt-conductr-tester/lagom-bundle/project/build.properties
sbt-conductr-tester/lagom-bundle/project/plugins.sbt

A common pattern is to deploy a play app as user facing and keep all lagom services internal. In that scenario the play app becomes a client of the lagom services.
In Lagom 1.2.x the LagomClient library didn't support that scenario so this PR is meant to help prevent regressions. This PR can't be backported to `2.2.x` because Lagom 1.2.x didn't support this scenario.

Promotes Play-service into a client of the Lagom-service

---

src/sbt-test/public/conduct-end-to-end/build.sbt
src/sbt-test/public/lagom-conductr-bundle-java-service/build.sbt

Backport of https://github.com/typesafehub/sbt-conductr/pull/246 to 2.2.x

Update scripted test assertions (2.2.x)

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

"start" is now supported as an alias to "run" as per user feedback desiring "start.
Sample output:
```
> sandbox run -h
usage: sandbox run IMAGE_VERSION [ARGS]
...
> sandbox start -h
usage: sandbox run IMAGE_VERSION [ARGS]
> conduct run -h
usage: conduct run [-h] [--scale SCALE] [--affinity AFFINITY]
...
> conduct start -h
usage: conduct run [-h] [--scale SCALE] [--affinity AFFINITY]
...
```

Command aliases

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/private/sandbox-all-args/test
src/sbt-test/private/sandbox-conductr-roles/build.sbt
src/sbt-test/private/sandbox-end-to-end/test
src/sbt-test/public/conduct-end-to-end/test

This is to update sbt-conductr to match with changes to `conduct info` as part of released version `1.1.0`.
From CLI version `1.1.0` the `conduct info` command accepts bundle id or bundle name as optional input argument, allowing inspection of bundle.

Update conduct info to inspect bundle

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
src/sbt-test/private/sandbox-all-args/test
src/sbt-test/private/sandbox-conductr-roles/build.sbt
src/sbt-test/private/sandbox-end-to-end/test
src/sbt-test/public/conduct-end-to-end/test

Backport of https://github.com/typesafehub/sbt-conductr/pull/250 to 2.2.x

Update conduct info to inspect bundle (#250)

---

README.md
src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
src/sbt-test/public/bundle-plugin-acl-no-service-name/build.sbt
src/sbt-test/public/bundle-plugin-basic/build.sbt
src/sbt-test/public/bundle-plugin-bundle-plugin-acl-empty-request-mapping/build.sbt
src/sbt-test/public/bundle-plugin-checks/build.sbt
src/sbt-test/public/bundle-plugin-overlays/build.sbt
src/sbt-test/public/play-bundle-plugin-custom-config/build.sbt
src/sbt-test/public/play-bundle-plugin-play24/build.sbt
src/sbt-test/public/play-bundle-plugin-play25/build.sbt

ConductR 2.1 tags are now used in place of compatibility version when producing packages. Tags are destined for human consumption, whereas compatibility versions are something that can help ConductR reason about whether a bundle with the same name is the same type of bundle e.g. when performing continuous delivery, it must be determined that a bundle can be replaced with another one. A default tag is generated from a project's version (compatibility versions also continue to be derived from a project's version).
Tag usage here is similar as per that found with Docker and git.
The README has also been updated for tags and slightly revised for an improvement in flow.

Introduces tags

---

src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
src/sbt-test/public/bundle-plugin-validation-acl-and-service/build.sbt

This commit permits the scenario where a string path and its rewrite path can be specified for all request methods. Without this fix, an sbt error would occur due to the enumeration "withName" method failing.

Permit string path and re-write path combinations

---

src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala

Update latest ConductR version to 2.0.5.
conductr-bundle-lib version stays at 1.5.0 to support Lagom 1.2.x projects.

Update versions (2.2.x)

---

src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
src/sbt-test/public/bundle-plugin-checks/build.sbt

Prior to this change, the name of the status component was derived from the bundle component. Example: A status component was named "my-bundle-status" if the bundle component name was "my-bundle". This logic makes it difficult to filter for the status component, especially if the bundle component contains the substring "status" as well.
Now, we name the status component always "bundle-status" to make it simplier to search for a status component, e.g. in the `conductr-cli` to auto-detect components.

Use name bundle-status for status component

---

src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
src/sbt-test/public/bundle-plugin-checks/build.sbt

Prior to this change, the name of the status component was derived from the bundle component. Example: A status component was named "my-bundle-status" if the bundle component name was "my-bundle". This logic makes it difficult to filter for the status component, especially if the bundle component contains the substring "status" as well.
Now, we name the status component always "bundle-status" to make it simplier to search for a status component, e.g. in the `conductr-cli` to auto-detect components.

Use name bundle-status for status component (2.2.x)

---

.travis.yml
src/sbt-test/private/sandbox-all-args/test
src/sbt-test/private/sandbox-conductr-roles/test
src/sbt-test/private/sandbox-end-to-end/test
src/sbt-test/public/conduct-end-to-end/test
src/sbt-test/public/lagom-conductr-bundle-java-service/test
src/sbt-test/public/sandbox-ports-override-endpoints/test

Backport of https://github.com/typesafehub/sbt-conductr/pull/266 to 2.2.x

Update tests to ConductR 2.0.5 (2.2.x)

---

sbt-conductr-tester/lagom-java-bundle/build.sbt
sbt-conductr-tester/lagom-java-bundle/project/plugins.sbt
sbt-conductr-tester/lagom-scala-bundle/build.sbt
sbt-conductr-tester/lagom-scala-bundle/lagom-service-impl/src/main/scala/impl/FooLoader.scala
sbt-conductr-tester/lagom-scala-bundle/play-service/app/PlayGatewayLoader.scala
sbt-conductr-tester/lagom-scala-bundle/project/plugins.sbt
src/sbt-test/public/conduct-end-to-end/build.sbt
src/sbt-test/public/lagom-bundle-plugin-multi-projects-single-acl/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-multi-projects/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-play-and-lagom-service-java/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-play-and-lagom-service-scala/lagom-service-impl/src/main/scala/impl/FooLoader.scala
src/sbt-test/public/lagom-bundle-plugin-play-and-lagom-service-scala/play-service/app/Loader.scala
src/sbt-test/public/lagom-bundle-plugin-play-and-lagom-service-scala/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-with-service-endpoint-java/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-with-service-endpoint-scala/project/plugins.sbt
src/sbt-test/public/lagom-bundle-plugin-with-service-endpoint-scala/simple-impl/src/main/scala/impl/FooLoader.scala
src/sbt-test/public/lagom-conductr-plugin-java-service/project/plugins.sbt
src/sbt-test/public/lagom-conductr-plugin-scala-service/lagom-service-impl/src/main/scala/impl/FooLoader.scala
src/sbt-test/public/lagom-conductr-plugin-scala-service/project/plugins.sbt

This requires working around the conflicting `circuitBreakerMetricsProvider` definitions in `ConductRServiceLocatorComponents` and `LagomServiceClientComponents`.
See typesafehub/conductr-lib#145 for details.

Update Lagom to 1.3.5 in tests

---

sbt-conductr-tester/play-bundle/project/plugins.sbt
src/main/scala/com/lightbend/conductr/sbt/package.scala
src/test/scala/com/lightbend/conductr/sbt/PackageSpec.scala

Now uses conductr-lib 2.0 for Akka 2.5 and Play 2.6 support.

Bump up the versions

---

.travis.yml
src/main/scala/com/lightbend/conductr/sbt/package.scala
src/sbt-test/private/sandbox-conductr-roles/test
src/sbt-test/private/sandbox-end-to-end/build.sbt
src/sbt-test/private/sandbox-end-to-end/test
src/sbt-test/public/conduct-end-to-end/test
src/sbt-test/public/lagom-conductr-plugin-java-service/test
src/sbt-test/public/lagom-conductr-plugin-legacy-java-service/test
src/sbt-test/public/lagom-conductr-plugin-legacy-scala-service/test
src/sbt-test/public/lagom-conductr-plugin-scala-service/test
src/sbt-test/public/sandbox-ports-override-endpoints/test

`conductr-lib` `2.1.0` will be released on Felix's Monday with support for Lagom 1.4. This updates `sbt-conductr` to use that version.

Version bump for Lagom 1.4
