typesafehub/sbt-conductr

- src/main/scala/com/typesafe/conductr/client/ConductRController.scala
- src/main/scala/com/typesafe/conductr/sbt/console/AnsiConsole.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Columns.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala
> Print replicated and starting bundle counds. Print hints.

- src/main/scala/com/typesafe/conductr/client/ConductRController.scala
- src/main/scala/com/typesafe/conductr/client/package.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Columns.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala
- src/test/scala/com/typesafe/conductr/TestBundle.scala
- src/test/scala/com/typesafe/conductr/client/ConductRControllerSpec.scala
> Handle bundle name

- src/main/scala/com/typesafe/conductr/sbt/console/Columns.scala
Just a quick fix for a problem I noticed when testing.
*P.S. I can't merge this. Need to be added to collaborators.*
> Fix length check when truncating column value

- .travis.yml
- README.md
- build.sbt
- project/Build.scala
- project/Dependencies.scala
- src/main/scala/com/typesafe/conductr/sbt/SbtTypesafeConductR.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala
- src/test/scala/com/typesafe/conductr/TestBundle.scala
Also: 
* Enforcement of JDK 6
* update to latest akka-contrib-extra
> Removal of scheduling params

- project/Dependencies.scala
- sbt-typesafe-conductr-tester/build.sbt
- src/main/scala/com/typesafe/conductr/sbt/SbtTypesafeConductR.scala
> Upgrades to sbt-bundle bytes dsl

- project/Dependencies.scala
- project/build.properties
- src/main/scala/com/typesafe/conductr/client/ConductRController.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala
> Update to streams M5

- src/sbt-test/sbt-conductr/basic/build.sbt
- src/sbt-test/sbt-conductr/basic/test
Enhance scripted tests with a task to check controlServer value.
Added a task to the build.sbt of the basic project in sbt-test
> Issue # 67.

- src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
sorry about that (git rebase etc.)
> Issue # 68. changed prompt from 'startBundle' to 'conduct start'

- README.md
- src/main/scala/com/typesafe/conductr/client/ConductRController.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
- src/test/scala/com/typesafe/conductr/client/ConductRControllerSpec.scala
Change subtask "start" to "run"
> Issue # 68

- src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
Removed sLog from ConductRPlugin.conductTask. Now using state.log.info(...) for task logging.
> Issue # 76

- src/main/scala/com/typesafe/conductr/client/ConductRController.scala
- src/main/scala/com/typesafe/conductr/client/package.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductRKeys.scala
- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Column.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Console.scala
- src/main/scala/com/typesafe/conductr/sbt/console/Screen.scala
- src/test/scala/com/typesafe/conductr/client/ConductRControllerSpec.scala
Events and logs JSON format is not yet known, therefore both commands only print a helpful message now.
> Events and logs

- README.md
- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
... in order to be consistent with the CLI
Fixes #105
> Introduces a scale flag

- src/main/scala/com/typesafe/conductr/sbt/ConductR.scala
This PR changes the `load bundle` logic. Instead of constructing the `LoadBundle` infos from the`BundleKeys`, the information are retrieved from the `bundle.conf`inside the bundle zip file.
If an additional configuration zip file (`configuration:dist`) is specified during `bundle load` then the infos of the `bundle.conf` inside the configuration zip file are used. These infos are overriding the values of the bundle.
This is the same logic as in the `conductr-cli`. It has been manually tested with and without additional configuration. Unit tests have not been provided, yet. First, @huntc should review the current approach. Afterwards I'll create tests for it.
> Merge bundle configurations

- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
- Better output in case sub command does not exist
- `Option` of `Parser[Option[ConductSubtask]]]` not necessary
- `conduct` without any sub command yields now the `conduct help` command
> Improving help command

- src/main/scala/com/typesafe/conductr/sbt/ConductRClient.scala
Remove a debugging message in `ConductRClient`
> Remove debugging messages

- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
For the following commands the available bundle names in the ConductR cluster are resolved and auto completed if the user presses the tab key:
- conduct run
- conduct stop
- conduct load
- conduct unload
- conduct logs
- conduct events
Fixes https://github.com/sbt/sbt-conductr/issues/43
The current solution runs `conduct info` to resolve the current bundle names of the running ConductR cluster. If no ConductR cluster is running then the exception if catched and an empty String is returned, meaning no auto completion is available. What is not so nice is that the `conduct info` command is executed every time the user hits the tab key when using the `conduct` command, i.e. `conduct info` is executed for `conduct run` as well as for `conduct load`, `conduct --help` and so on. This slows down …
> Auto complete bundle names

- src/main/scala/com/typesafe/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/sbt-conductr/conduct-common-opts/test
- src/sbt-test/sbt-conductr/conduct-end-to-end/test
Now it is possible to:
- specify optional options before and after positional arguments
- Tab completion also works if optional arguments are specified
- Tab completion of optional arguments are working if the argument is the only left choice, e.g. `--api-v <TAB>` is autocompleting to `--api-version `
> Enhance parser

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
Making `sandbox run` and `sandbox stop` public so that `conductr` can use these methods in their acceptance tests.
> Public sandbox run and stop methods

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/lagom-conductr-bundle/play-and-lagom-service/test
- src/sbt-test/sbt-conductr/conduct-end-to-end/test
- src/sbt-test/sbt-conductr/sandbox-all-args/test
- src/sbt-test/sbt-conductr/sandbox-conductr-roles/test
- src/sbt-test/sbt-conductr/sandbox-ports-basic/test
- src/sbt-test/sbt-conductr/sandbox-ports-multi-module/test
- src/sbt-test/sbt-conductr/sandbox-ports-override-endpoints/test
- src/sbt-test/sbt-conductr/sandbox-scaling/test
- src/sbt-test/sbt-conductr/sandbox-with-features/test
- src/sbt-test/sbt-conductr/sandbox-with-lagom-project/test
- src/sbt-test/sbt-conductr/sandbox-with-play-project/test
- src/sbt-test/sbt-conductr/sandbox-with-scala-project/test
Update latest ConductR version to 1.1.11
> Update ConductR to 1.1.11

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/sbt-conductr/sandbox-all-args/test
- Removing the sandbox init command
- Adding the sandbox version command
> Update sandbox commands

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
This commit adds support for forwarding arguments `envsCore`, `envsAgent`, `args`, `argsCore`, `argsAgent` to the `sandbox` command.
Manual test (SBT CLI):
`sandbox run 2.0.0 --arg arg1 --arg arg2 --arg-agent argagent1 --arg-agent argagent2 --arg-core argcore1 --arg-core argcore2 --env-agent AGENT1=test --env-agent AGENT2=test --env-core CORE1=test --env-core CORE2=test`
Check process (Bash)
```
~/work/lightbend/sbt-conductr#argsenvs $ ps aux | grep "[s]andbox run"
longsho+ 22933  1.8  0.0  82928 31776 pts/7    S+   17:56   0:00 /usr/bin/python3 /home/longshorej/.local/bin/sandbox run 2.0.0 --env-core CORE1=test --env-core CORE2=test --env-agent AGENT1=test --env-agent AGENT2=test --arg arg1 --arg arg2 --arg-core argcore1 --arg-core argcore2 --arg-agent argagent1 --arg-agent argagent2
```
> Add support for envsCore, envsAgent, args, argsCore, argsAgent

- .travis.yml
- README.md
- src/main/scala/com/lightbend/conductr/sbt/ConductRImport.scala
- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/sbt-conductr/conduct-common-args/test
- src/sbt-test/sbt-conductr/sandbox-all-args/test
- src/sbt-test/sbt-conductr/sandbox-conductr-roles/test
- src/sbt-test/sbt-conductr/sandbox-end-to-end/test
Cherry pick of https://github.com/typesafehub/sbt-conductr/pull/209 for 2.2.x
> Cherry pick #209

- src/sbt-test/lagom-conductr-bundle/lagom-java-service/build.sbt
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/lagom-service-api/src/main/java/api/FooService.java
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/lagom-service-impl/src/main/java/impl/FooServiceImpl.java
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/project/Build.scala
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/project/build.properties
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/project/plugins.sbt
- src/sbt-test/lagom-conductr-bundle/lagom-java-service/test
> Deploy and run a LagomJava service (2.2.x)

- src/sbt-test/public/conduct-end-to-end/build.sbt
- src/sbt-test/public/lagom-conductr-plugin-java-service/build.sbt
- src/sbt-test/public/lagom-conductr-plugin-scala-service/build.sbt
Update scripted test assertions to reflect `conduct info` command changes in PR https://github.com/typesafehub/conductr-cli/pull/352.
> Update scripted test assertions

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
Cherry pick of https://github.com/typesafehub/sbt-conductr/pull/245 for branch 2.2.x
> Command aliases (2.2.x)

- README.md
- src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
- src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
- src/sbt-test/public/bundle-plugin-acl-empty-request-mapping/build.sbt
- src/sbt-test/public/bundle-plugin-acl-no-service-name/build.sbt
- src/sbt-test/public/bundle-plugin-basic/build.sbt
- src/sbt-test/public/bundle-plugin-checks/build.sbt
- src/sbt-test/public/bundle-plugin-overlays/build.sbt
- src/sbt-test/public/play-bundle-plugin-custom-config/build.sbt
- src/sbt-test/public/play-bundle-plugin-play24/build.sbt
- src/sbt-test/public/play-bundle-plugin-play25/build.sbt
Cherry pick of #252 for the 2.2 branch
> Introduces tags

- README.md
- sbt-conductr-tester/bundle/build.sbt
- src/main/scala/com/lightbend/conductr/sbt/BundleImport.scala
- src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala
- src/sbt-test/public/bundle-plugin-acl-no-service-name/build.sbt
- src/sbt-test/public/bundle-plugin-basic/build.sbt
- src/sbt-test/public/bundle-plugin-bundle-plugin-acl-empty-request-mapping/build.sbt
- src/sbt-test/public/bundle-plugin-checks/build.sbt
- src/sbt-test/public/bundle-plugin-overlays/build.sbt
- src/sbt-test/public/play-bundle-plugin-custom-config/build.sbt
- src/sbt-test/public/play-bundle-plugin-play24/build.sbt
- src/sbt-test/public/play-bundle-plugin-play25/build.sbt
Annotations are supported by the forthcoming ConductR 2.1.
> Introduce annotations

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/public/conduct-common-args/test
- src/sbt-test/public/conduct-end-to-end/test
Adding the following conduct commands:
> Additional conduct commands

- src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala
- src/sbt-test/public/conduct-common-args/test
- src/sbt-test/public/conduct-end-to-end/test
Backport to 2.2.x of PR https://github.com/typesafehub/sbt-conductr/pull/264.
> Additional conduct commands (2.2.x)

- src/main/scala/com/lightbend/conductr/sbt/package.scala
- src/sbt-test/public/lagom-bundle-plugin-with-service-endpoint-scala/simple-impl/src/main/scala/impl/FooLoader.scala
> Bumps conductr-lib to avoid metricsProvider override.

- project/Dependencies.scala
This includes improved Docker support.
> Update sbt-native-packager to version 1.3.2
